<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="6" total="6" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="19505" started-at="2016-07-27T09:03:03Z" finished-at="2016-07-27T09:03:22Z">
    <groups>
    </groups>
    <test name="商户普通买票退票" duration-ms="6673" started-at="2016-07-27T09:03:03Z" finished-at="2016-07-27T09:03:09Z">
      <class name="com.busAPP_IOS.run.RunTestCase">
        <test-method status="PASS" signature="beforClass()[pri:0, instance:com.busAPP_IOS.run.RunTestCase@417cc8df]" name="beforClass" is-config="true" duration-ms="636" started-at="2016-07-27T17:03:03Z" finished-at="2016-07-27T17:03:03Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforClass -->
        <test-method status="FAIL" signature="senic_order()[pri:0, instance:com.busAPP_IOS.run.RunTestCase@417cc8df]" name="senic_order" duration-ms="6027" started-at="2016-07-27T17:03:03Z" description="商户普通买票退票" finished-at="2016-07-27T17:03:09Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at com.busAPP_IOS.run.RunTestCase.logout(RunTestCase.java:240)
	at com.busAPP_IOS.run.RunTestCase.runTestCase(RunTestCase.java:103)
	at com.busAPP_IOS.run.RunTestCase.senic_order(RunTestCase.java:25)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:335)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:330)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- senic_order -->
      </class> <!-- com.busAPP_IOS.run.RunTestCase -->
    </test> <!-- 商户普通买票退票 -->
    <test name="商户演艺买票退票" duration-ms="2670" started-at="2016-07-27T09:03:10Z" finished-at="2016-07-27T09:03:12Z">
      <class name="com.busAPP_IOS.run.RunTestCase">
        <test-method status="PASS" signature="beforClass()[pri:0, instance:com.busAPP_IOS.run.RunTestCase@251d737b]" name="beforClass" is-config="true" duration-ms="8" started-at="2016-07-27T17:03:10Z" finished-at="2016-07-27T17:03:10Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforClass -->
        <test-method status="FAIL" signature="acting_senic_order()[pri:0, instance:com.busAPP_IOS.run.RunTestCase@251d737b]" name="acting_senic_order" duration-ms="2661" started-at="2016-07-27T17:03:10Z" description="商户演艺买票退票" finished-at="2016-07-27T17:03:12Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at com.busAPP_IOS.run.RunTestCase.logout(RunTestCase.java:240)
	at com.busAPP_IOS.run.RunTestCase.runTestCase(RunTestCase.java:103)
	at com.busAPP_IOS.run.RunTestCase.acting_senic_order(RunTestCase.java:30)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:335)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:330)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- acting_senic_order -->
      </class> <!-- com.busAPP_IOS.run.RunTestCase -->
    </test> <!-- 商户演艺买票退票 -->
    <test name="商户通用买票退票" duration-ms="2446" started-at="2016-07-27T09:03:12Z" finished-at="2016-07-27T09:03:15Z">
      <class name="com.busAPP_IOS.run.RunTestCase">
        <test-method status="PASS" signature="beforClass()[pri:0, instance:com.busAPP_IOS.run.RunTestCase@4c0da7c3]" name="beforClass" is-config="true" duration-ms="13" started-at="2016-07-27T17:03:12Z" finished-at="2016-07-27T17:03:12Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforClass -->
        <test-method status="FAIL" signature="universal_scenic_order()[pri:0, instance:com.busAPP_IOS.run.RunTestCase@4c0da7c3]" name="universal_scenic_order" duration-ms="2431" started-at="2016-07-27T17:03:12Z" description="商户通用买票退票" finished-at="2016-07-27T17:03:15Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at com.busAPP_IOS.run.RunTestCase.logout(RunTestCase.java:240)
	at com.busAPP_IOS.run.RunTestCase.runTestCase(RunTestCase.java:103)
	at com.busAPP_IOS.run.RunTestCase.universal_scenic_order(RunTestCase.java:35)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:335)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:330)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- universal_scenic_order -->
      </class> <!-- com.busAPP_IOS.run.RunTestCase -->
    </test> <!-- 商户通用买票退票 -->
    <test name="导游普通买票退票" duration-ms="2414" started-at="2016-07-27T09:03:15Z" finished-at="2016-07-27T09:03:17Z">
      <class name="com.busAPP_IOS.run.RunTestCase">
        <test-method status="PASS" signature="beforClass()[pri:0, instance:com.busAPP_IOS.run.RunTestCase@1af6a7cd]" name="beforClass" is-config="true" duration-ms="7" started-at="2016-07-27T17:03:15Z" finished-at="2016-07-27T17:03:15Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforClass -->
        <test-method status="FAIL" signature="cube_senic_order()[pri:0, instance:com.busAPP_IOS.run.RunTestCase@1af6a7cd]" name="cube_senic_order" duration-ms="2404" started-at="2016-07-27T17:03:15Z" description="导游普通买票退票" finished-at="2016-07-27T17:03:17Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at com.busAPP_IOS.run.RunTestCase.logout(RunTestCase.java:240)
	at com.busAPP_IOS.run.RunTestCase.runTestCase(RunTestCase.java:103)
	at com.busAPP_IOS.run.RunTestCase.cube_senic_order(RunTestCase.java:40)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:335)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:330)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- cube_senic_order -->
      </class> <!-- com.busAPP_IOS.run.RunTestCase -->
    </test> <!-- 导游普通买票退票 -->
    <test name="导游演艺买票退票" duration-ms="2449" started-at="2016-07-27T09:03:17Z" finished-at="2016-07-27T09:03:20Z">
      <class name="com.busAPP_IOS.run.RunTestCase">
        <test-method status="PASS" signature="beforClass()[pri:0, instance:com.busAPP_IOS.run.RunTestCase@607e334]" name="beforClass" is-config="true" duration-ms="6" started-at="2016-07-27T17:03:17Z" finished-at="2016-07-27T17:03:17Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforClass -->
        <test-method status="FAIL" signature="cube_acting_senic_order()[pri:0, instance:com.busAPP_IOS.run.RunTestCase@607e334]" name="cube_acting_senic_order" duration-ms="2441" started-at="2016-07-27T17:03:17Z" description="导游演艺买票退票" finished-at="2016-07-27T17:03:20Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at com.busAPP_IOS.run.RunTestCase.logout(RunTestCase.java:240)
	at com.busAPP_IOS.run.RunTestCase.runTestCase(RunTestCase.java:103)
	at com.busAPP_IOS.run.RunTestCase.cube_acting_senic_order(RunTestCase.java:45)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:335)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:330)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- cube_acting_senic_order -->
      </class> <!-- com.busAPP_IOS.run.RunTestCase -->
    </test> <!-- 导游演艺买票退票 -->
    <test name="导游通用买票退票" duration-ms="2318" started-at="2016-07-27T09:03:20Z" finished-at="2016-07-27T09:03:22Z">
      <class name="com.busAPP_IOS.run.RunTestCase">
        <test-method status="PASS" signature="beforClass()[pri:0, instance:com.busAPP_IOS.run.RunTestCase@1efb2d90]" name="beforClass" is-config="true" duration-ms="5" started-at="2016-07-27T17:03:20Z" finished-at="2016-07-27T17:03:20Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforClass -->
        <test-method status="FAIL" signature="cube_universal_scenic_order()[pri:0, instance:com.busAPP_IOS.run.RunTestCase@1efb2d90]" name="cube_universal_scenic_order" duration-ms="2310" started-at="2016-07-27T17:03:20Z" description="导游通用买票退票" finished-at="2016-07-27T17:03:22Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at com.busAPP_IOS.run.RunTestCase.logout(RunTestCase.java:240)
	at com.busAPP_IOS.run.RunTestCase.runTestCase(RunTestCase.java:103)
	at com.busAPP_IOS.run.RunTestCase.cube_universal_scenic_order(RunTestCase.java:50)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:335)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:330)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- cube_universal_scenic_order -->
      </class> <!-- com.busAPP_IOS.run.RunTestCase -->
    </test> <!-- 导游通用买票退票 -->
  </suite> <!-- Suite -->
</testng-results>
